title = "Refactor Or Die"

baseURL = "https://refactorordie.github.io/website/public"
footnoteReturnLinkContents = "↩"
staticDir = ["static"]

newContentEditor = "code"

pygmentsUseClasses = true

[outputs]
  home = ["HTML", "JSON", "RSS"]
  page = ["HTML", "JSON"]

# [permalinks]
#   post = "/:year/:month/:title/"