title = "Refactor Or Die"

baseURL = "https://refactorordie.com"
footnoteReturnLinkContents = "↩"
staticDir = ["static"]

newContentEditor = "code"

pygmentsUseClasses = true

[outputs]
  home = ["HTML", "JSON", "RSS"]
  page = ["HTML", "JSON"]
